<?php

/**
 * @file
 * Hook implementation(s) for islandora_access.
 */

/**
 * Implements hook_menu().
 */
function islandora_owner_access_menu() {
  $item = array();
  $items['admin/islandora/islandora_access'] = array(
    'title' => 'Islandora Owner Access Admin',
    'description' => 'Determine access to object manage permissions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_owner_access_user_admin'),
    'access arguments' => array('administer permissions'),
    'file' => 'includes/islandora_owner_access.admin.inc',
  );
  return $items;

}
/**
 * Implements hook_islandora_object_access().
 *
 * Allow management to objects submitters own.
 */
function islandora_owner_access_islandora_object_access($op, $object, $user) {
  $management_operations = array(
    ISLANDORA_VIEW_OBJECTS,
    ISLANDORA_INGEST,
  );

  $role_name = variable_get('islandora_owner_access_role', '');
  $has_owner_access = $user->name == $object->owner && in_array($role_name, $user->roles);

  $has_admin_access = in_array("administrator", $user->roles);

  $has_management_access = in_array($op, $management_operations);

  return $has_owner_access || $has_admin_access || $has_management_access;

}
